Repository HSU-Likelion13-Storey/Storey-Front, pull requests merged in 2025-08, with the labels that each got.

#5 Feat/mypage: 마이 페이지, Footer UI 구현 #3
  src/App.jsx
  src/assets/index.js
  src/assets/logo-shadow.svg
  src/assets/mascot-happy.svg
  src/assets/profile.svg
  src/components/Layout.jsx
  src/components/common/Footer.jsx
  src/components/common/Footer.scss
  src/components/common/Modal.jsx
  src/components/common/Modal.scss
  src/components/mypage/MyPageScreen.jsx
  src/components/mypage/MyPageScreen.scss
  src/components/mypage/collection/Collection.jsx
  src/components/mypage/collection/Collection.scss
  src/components/mypage/download/Download.jsx
  src/components/mypage/download/Download.scss
  src/components/mypage/subscribe/Subscribe.jsx
  src/components/mypage/subscribe/Subscribe.scss
  src/pages/mypage/CollectionPage.jsx
  src/pages/mypage/DownloadPage.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/SubscribePage.jsx
  src/styles/_variables.scss
Labels: enhancement

#17 Feat/b2b event: 깜짝 이벤트 등록 페이지 UI 및 기능 구현 #14
  src/App.jsx
  src/assets/bubble.svg
  src/assets/index.js
  src/components/b2b/event-upload/EventUpload.jsx
  src/components/b2b/event-upload/EventUpload.module.scss
  src/components/b2b/home/B2BHomeScreen.jsx
  src/components/b2b/mypage/download/Download.jsx
  src/components/b2b/mypage/subscribe/Subscribe.jsx
  src/components/common/Footer.scss
  src/components/common/Modal.jsx
  src/components/common/Modal.scss
  src/components/user/Home/UserHome.jsx
  src/components/user/character-detail/CharacterDetail.jsx
  src/components/user/character-detail/CharacterDetail.module.scss
  src/components/user/share-char/Capture.module.scss
  src/components/user/share-char/Share.module.scss
  src/pages/b2b/EventUploadPage.jsx
  src/styles/_function.scss
Labels: enhancement

#21 Feat/mypage-change: 마이페이지 UI 수정 #18
  src/App.jsx
  src/assets/empty-logo.svg
  src/assets/index.js
  src/components/Layout.jsx
  src/components/b2b/mypage/B2BMyPageScreen.jsx
  src/components/b2b/mypage/B2BMyPageScreen.scss
  src/components/b2b/mypage/MyPageScreen.jsx
  src/components/b2b/mypage/MyPageScreen.scss
  src/components/b2b/mypage/download/Download.jsx
  src/components/b2b/mypage/subscribe/Subscribe.jsx
  src/components/b2b/mypage/subscribe/Subscribe.scss
  src/components/b2b/mypage/subscribe/SubscribeList.jsx
  src/components/b2b/mypage/subscribe/SubscribeList.module.scss
  src/components/common/Footer.jsx
  src/components/common/mypage/MyPageListItem.jsx
  src/components/common/mypage/MyPageListItem.scss
  src/components/common/mypage/Profile.jsx
  src/components/common/mypage/Profile.scss
  src/components/user/character-detail/CharacterDetail.jsx
  src/components/user/character-detail/CharacterDetail.module.scss
  src/components/user/mypage/UserMyPageScreen.jsx
  src/components/user/mypage/UserMyPageScreen.scss
  src/components/user/mypage/collection/Collection.jsx
  src/components/user/mypage/collection/Collection.scss
  src/pages/b2b/B2BMyPage.jsx
  src/pages/user/UserMyPage.jsx
  src/styles/global.scss
Labels: enhancement

#24 Fix/b2b home: 사장님 Home 페이지 수정기능 구현
  src/App.jsx
  src/assets/questionIcon.svg
  src/components/b2b/home/B2BHomePreScreen.jsx
  src/components/b2b/home/B2BHomePreScreen.scss
  src/components/b2b/home/B2BHomeScreen.jsx
  src/components/b2b/home/B2BHomeScreen.scss
  src/components/b2b/home/CharacterBlock.jsx
  src/components/b2b/home/CharacterBlock.scss
  src/components/b2b/home/EmptyStateCard.jsx
  src/components/b2b/home/EmptyStateCard.scss
  src/components/b2b/home/SummaryBlock.jsx
  src/components/b2b/home/SummaryBlock.scss
  src/pages/b2b/B2BHomePage.jsx
  src/pages/b2b/B2BHomePrePage.jsx
Labels: enhancement, fix

#29 Feat/splash: 스플래쉬 화면 UI 및 기능 구현 #26
  src/assets/index.js
  src/assets/mascot-bubble-splash.svg
  src/components/common/splash/Splash.jsx
  src/components/common/splash/Splash.module.scss
  src/hooks/useSplash.js
  src/pages/auth/LoginPage.jsx
  src/pages/b2b/B2BHomePage.jsx
  src/pages/user/UserHomePage.jsx
  src/styles/global.scss
Labels: enhancement

#40 Feat/pwa: Favicon 설정 및 PWA 적용 #37
  index.html
  package-lock.json
  package.json
  public/.gitkeep
  public/favicons/apple-touch-icon.png
  public/favicons/favicon-96x96.png
  public/favicons/favicon.ico
  public/favicons/favicon.svg
  public/favicons/site.webmanifest
  public/favicons/web-app-manifest-192x192.png
  public/favicons/web-app-manifest-512x512.png
  vite.config.js
Labels: enhancement

#49 Fix/hkmo-design: 일부 스타일 및 UI 수정 #48
  src/components/b2b/event-upload/EventUpload.module.scss
  src/components/b2b/mypage/B2BMyPageScreen.jsx
  src/components/b2b/mypage/B2BMyPageScreen.module.scss
  src/components/b2b/mypage/download/Download.scss
  src/components/b2b/mypage/subscribe/Subscribe.scss
  src/components/b2b/mypage/subscribe/SubscribeList.module.scss
  src/components/user/character-detail/CharacterDetail.jsx
  src/components/user/character-detail/CharacterDetail.module.scss
  src/components/user/mypage/UserMyPageScreen.jsx
  src/components/user/mypage/UserMyPageScreen.scss
  src/components/user/mypage/collection/Collection.scss
  src/components/user/qr-scan/QrScan.scss
  src/components/user/share-char/Capture.module.scss
  src/components/user/share-char/Share.module.scss
Labels: fix
